export const enum CacheKey {
  ANNOUNCEMENTS = 'whiteboardapp/announcements',
  INDIVIDUAL_ANNOUNCEMENT = 'whiteboardapp/announcement',
  ASSIGNMENTS = 'whiteboardapp/assignments',
  INDIVIDUAL_ASSIGNMENT = 'whiteboardapp/assignment',
  EVENTS = 'whiteboardapp/events',
  INDIVIDUAL_EVENT = 'whiteboardapp/event',
  COURSES = 'whiteboardapp/courses',
  INDIVIDUAL_COURSE = 'whiteboardapp/course',
  COURSE_DESCRIPTION = 'whiteboardapp/course-description',
  COURSE_MEMBERS = 'whiteboardapp/course-members',
  INDIVIDUAL_COURSE_MEMBER = 'whiteboardapp/course-member',
  COURSE_BOARDS = 'whiteboardapp/course-boards',
  INDIVIDUAL_COURSE_BOARD = 'whiteboardapp/course-board',
}
