export const enum CacheKey {
  ANNOUNCEMENTS = 'whiteboardapp/announcements',
  INDIVIDUAL_ANNOUNCEMENT = 'whiteboardapp/announcement',
  ALL_ANNOUNCEMENTS = 'whiteboardapp/all-announcements',
  ASSIGNMENTS = 'whiteboardapp/assignments',
  INDIVIDUAL_ASSIGNMENT = 'whiteboardapp/assignment',
  ALL_ASSIGNMENTS = 'whiteboardapp/all-assignments',
  EVENTS = 'whiteboardapp/events',
  INDIVIDUAL_EVENT = 'whiteboardapp/event',
  COURSES = 'whiteboardapp/courses',
  INDIVIDUAL_COURSE = 'whiteboardapp/course',
  COURSE_DESCRIPTION = 'whiteboardapp/course-description',
  COURSE_MEMBERS = 'whiteboardapp/course-members',
  INDIVIDUAL_COURSE_MEMBER = 'whiteboardapp/course-member',
  COURSE_BOARDS = 'whiteboardapp/course-boards',
  COURSE_BOARD_MESSAGES = 'whiteboardapp/course-board-messages',
  INDIVIDUAL_COURSE_BOARD = 'whiteboardapp/course-board',
  RECENT_DIRECT_MESSAGES = 'whiteboardapp/recent-direct-messages',
  DIRECT_MESSAGES = 'whiteboardapp/direct-messages',
  USER_PROFILES = 'whiteboardapp/user-profiles',
  CURRENT_USER_PROFILE = 'whiteboardapp/current-user-profile',
}
