name: CI

on:
  push:
    paths:
      - src/**
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-types:
    name: Verify TypeScript types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --frozen-lockfile

      - run: pnpm verify-types
